FROM golang:1.20-alpine as builder

WORKDIR /app

COPY main.go /app

# Build the Go application for prodcution
RUN go build main.go

EXPOSE 8080

# Run the application when the container starts for production
CMD ["./main"]

FROM scratch
WORKDIR /app
COPY --from=builder /app /app
CMD [ "./main" ]